# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myFastLM <- function(X, y) {
    .Call(`_testPackage_myFastLM`, X, y)
}

parallel_random_matrix <- function(m, n, seedRaw) {
    .Call(`_testPackage_parallel_random_matrix`, m, n, seedRaw)
}

